apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: dev
type: Opaque
stringData:
  AUTH0_CLIENT_SECRET: "FlECkJHltSuDb7h9gMDBSnfbx2AVbnS0mU9y8_OnE4naLVMH_tE9-JrZDYDOHDqd"
  AUTH0_SECRET: "2b259401c2f4627ebf94baee9c87ad5f9f29ed2ee0d46f53c74d88a49d8fed60"