apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: dev
data:
  DB_HOST: "user-db"
  DB_PORT: "5432"
  DB_NAME: "users"
  AUTH0_DOMAIN: "dev-jfk0z7pf4l611euv.us.auth0.com"
  AUTH0_AUDIENCE: "https://task-reminder-api/"
